import type { Metadata } from "next";
import "./globals.css";
import Header from "./components/complex/header/Header";
import Footer from "./components/complex/footer/Footer";


export const metadata: Metadata = {
  title: "Новая походка",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      >
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
